// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
     
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDg-2Brj8sN5eVvLM6B1SuBbPUz6fO_P9w',
    appId: '1:499304840885:web:a737ec813fcbd0ef0f08fc',
    messagingSenderId: '499304840885',
    projectId: 'registroincidencias-9e4f5',
    authDomain: 'registroincidencias-9e4f5.firebaseapp.com',
    storageBucket: 'registroincidencias-9e4f5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAelKMlVi23_l_JOcDhM7o-DTp4QLnV-pE',
    appId: '1:499304840885:android:62219ce053b4c3890f08fc',
    messagingSenderId: '499304840885',
    projectId: 'registroincidencias-9e4f5',
    storageBucket: 'registroincidencias-9e4f5.firebasestorage.app',
  );
}
